<template>
  <div class="view view-flashes">
    <div class="fixed-width-container">
      <div class="performances">
        <!-- the following should be generated by a v-for loop with all the available maps -->
        <div class="performance" :class="{active: activeMap == 0}">
          <img
            class="map-image"
            src="https://test.mentor.gg/Content/Images/Overview/de_overpass.jpg"
          >
          <p class="map-name">Overpass</p>

          <div class="z-layer-lo">
            <span class="split-title">USES</span>
            <div class="split">
              <div class="ct">
                <img src="@/assets/ct_logo.png">
                <span>11%</span>
              </div>
              <div class="t">
                <img src="@/assets/t_logo.png">
                <span>65%</span>
              </div>
            </div>
          </div>

          <div class="z-layer-hi">
            <span class="split-title">ASSISTS</span>
            <div class="split">
              <div class="ct">
                <img src="@/assets/ct_logo.png">
                <span>11%</span>
              </div>
              <div class="t">
                <img src="@/assets/t_logo.png">
                <span>65%</span>
              </div>
            </div>

            <span class="split-title">BLINDED</span>
            <div class="split">
              <div class="ct">
                <img src="@/assets/ct_logo.png">
                <span>0.37</span>
              </div>
              <div class="t">
                <img src="@/assets/t_logo.png">
                <span>0.69</span>
              </div>
            </div>
          </div>
        </div>

        <div class="performance">
          <img
            class="map-image"
            src="https://test.mentor.gg/Content/Images/Overview/de_overpass.jpg"
          >
          <p class="map-name">Overpass</p>

          <div class="z-layer-lo">
            <span class="split-title">USES</span>
            <div class="split">
              <div class="ct">
                <img src="@/assets/ct_logo.png">
                <span>11%</span>
              </div>
              <div class="t">
                <img src="@/assets/t_logo.png">
                <span>65%</span>
              </div>
            </div>
          </div>

          <div class="z-layer-hi">
            <span class="split-title">ASSISTS</span>
            <div class="split">
              <div class="ct">
                <img src="@/assets/ct_logo.png">
                <span>11%</span>
              </div>
              <div class="t">
                <img src="@/assets/t_logo.png">
                <span>65%</span>
              </div>
            </div>

            <span class="split-title">BLINDED</span>
            <div class="split">
              <div class="ct">
                <img src="@/assets/ct_logo.png">
                <span>0.37</span>
              </div>
              <div class="t">
                <img src="@/assets/t_logo.png">
                <span>0.69</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="interactive-area">
        <div class="l bordered-box">
          <button class="button-variant-bordered" @click="OnShowTrajectories">Show Trajectories</button>
          <div class="team-select">
            <img class="t" src="@/assets/t_logo.png" :class="{active: activeTeam == 'T'}" @click="activeTeam = 'T'">
            <img class="ct" src="@/assets/ct_logo.png" :class="{active: activeTeam == 'CT'}" @click="activeTeam = 'CT'">
          </div>
          <CustomSelect :value="matchCount" :options="matchCountSelectOptions"></CustomSelect>
        </div>

        <div class="r bordered-box"></div>
      </div>
    </div>
  </div>
</template>

<script>
import CustomSelect from "@/components/CustomSelect.vue";

export default {
  components: {
    CustomSelect
  },
  mounted() {
    //initialization stuff here
  },
  data() {
    return {
      activeMap: 0,
      activeTeam: 'T',
      matchCount: 10,
      matchCountSelectOptions: {
        5: 'Use last 5 matches',
        10: 'Use last 10 matches',
        50: 'Use last 50 matches',
        100: 'Use last 100 matches',
      }
    };
  },
  methods: {
    OnShowTrajectories: function() {
      alert("Not Implemented");
    }
  }
};
</script>

<style lang="scss">
.view-flashes {
  margin-top: 40px;
}

.performances {
  display: flex;
  flex-direction: row;

  .performance {
    width: calc(100% / 7);
    margin-right: 20px;
    background-position: center;
    background-size: cover;
    position: relative;
    z-index: 1;
    overflow: hidden;
    border: 1px solid $purple;
    border-radius: 4px;
    cursor: pointer;

    &.active,
    &:hover {
      &:after {
        background: rgba(0, 0, 0, 0.3);
      }

      .map-image {
        filter: blur(2px) grayscale(0%);
      }
    }

    &:after {
      content: "";
      position: absolute;
      left: 0;
      top: 0;
      height: 100%;
      width: 100%;
      background: rgba(0, 0, 0, 0.7);
      pointer-events: none;
      z-index: -1;
      transition: 0.35s;
    }

    .map-image {
      position: absolute;
      width: 100%;
      height: 100%;
      z-index: -2;
      object-fit: cover;
      object-position: center;
      transition: 0.35s;
      filter: blur(2px) grayscale(100%);
    }

    .map-name {
      color: white;
      font-weight: 700;
      font-size: 1.125rem;
      margin: 5px 0;
      padding: 10px;
    }

    .split-title {
      color: $gray;
      font-size: 8px;
      margin-bottom: 1em;
      display: block;
      font-weight: 600;
    }

    .z-layer-lo {
      padding: 0 10px;
      padding-bottom: 20px;
    }

    .z-layer-hi {
      background: $dark-1;
      padding: 20px 10px;
      opacity: 0.8;
      position: relative;

      .split {
        &:first-of-type {
          border-bottom: 1px solid $purple;
          padding-bottom: 20px;
          margin-bottom: 20px;
        }
      }
    }

    .split {
      display: flex;
      justify-content: space-between;
      font-size: 12px;

      .ct,
      .t {
        display: flex;
        align-items: center;

        span {
          margin-left: 5px;
          color: white;
        }

        img {
          width: 18px;
          height: 18px;
        }
      }
    }
  }
}

.interactive-area {
  display: flex;
  justify-content: space-between;
  margin-top: 20px;

  .l {
    width: 65%;
    display: flex;
    align-items: center;
    justify-content: space-between;

    .team-select {

      img {
        margin: 0 5px;
      }

      .t {
        transition: 0.35s;
        cursor: pointer;

        &.active,
        &:hover {
          filter: drop-shadow(0px 0px 4px rgb(168, 153, 102));
        }
      }

      .ct {
        transition: 0.35s;
        cursor: pointer;

        &.active,
        &:hover {
          filter: drop-shadow(0px 0px 4px rgb(61, 120, 204));
        }
      }
    }
  }

  .r {
    width: 30%;
  }
}
</style>